---
# ______________________________________________________________ #
#         Config file for the onboardme cli command.             #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#  - If this files exists as: ~/.config/onboardme/config.yaml    #
#    then its loaded instead of the default config               #
# -------------------------------------------------------------- #


log:
  # Full path to a file you'd like to log to. Creates file if it doesn't exist
  file: ""
  # what level of logs to output (debug, info, warn, error)
  level: "warn"

# steps refer to a specific function in the list of functions we run
steps:
  # these are mac specific steps
  Darwin:
    - dot_files
    - packages
    - font_setup
    - neovim_setup
    - sudo_setup
  # these are linux specific steps
  Linux:
    - dot_files
    - packages
    - font_setup
    - neovim_setup
    - group_setup

dot_files:
  # personal git repo URL for your dot files, defaults to jessebot/dot_files
  git_url: "https://github.com/jessebot/dot_files.git"
  # the branch to use for the git repo above, defaults to main
  git_branch: "main"
  # this is where the actual git config for your dot files lives
  # it can't live in ~/.git because that will affect _everything_ under ~/
  git_config_dir: "~/.config/dot_files"
  # !!CAREFUL: runs a `git reset --hard`, which will overwite/delete files in 
  # $HOME that conflict with the above defined git repo url and branch.
  # You should run the following to get the files that would be overwritten:
  # onboardme -s dot_files
  # if set to true, then using onboardme -O will toggle it back to false
  overwrite: false

# This is the basic package config.
package:
  # Remove any of the below pkg managers to only run the remaining pkg managers
  managers:
    # macOS specific steps
    Darwin:
      - brew
      - pip3.11
    # Debian/Ubuntu specific steps
    Linux:
      - apt
      - brew
      - pip3.11
      - flatpak
      - snap
  # list of extra existing packages groups to install
  groups:
    default:
      # basic tui stuff to have a nice time in the terminal :)
      - default
    # move these package.groups.default to always install them
    optional:
      # setting up more python data science specific tooling
      - data_science
      # kubernetes and docker tools
      - devops
      # gaming always installs gui
      - gaming
      # freetube and other gui applications
      - gui
      # this configures neomutt and offlineimap
      - mail
      # sets up useful music tui stuff for spotify and youtube
      - music
      # things like zoom and slack
      - work

# known safe remote hosts that you expect to be able to ping and SSH into
remote_hosts: []
  # - 192.168.42.42

# setup iptable on Linux only
firewall: false

### TODO: make this work, it's a nice dream though.
# any URL we can curl to download a folder from
# wallpapers_download_url: ""
